version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./SockJS.NET/syp.biz/SockJS.NET/syp.biz.SockJS.NET.Client/syp.biz.SockJS.NET.Client.csproj --verbosity m
  - cmd: dotnet restore ./SockJS.NET/syp.biz/SockJS.NET/syp.biz.SockJS.NET.Common/syp.biz.SockJS.NET.Common.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./SockJS.NET/syp.biz/SockJS.NET/syp.biz.SockJS.NET.Client/syp.biz.SockJS.NET.Client.csproj
  - cmd: dotnet publish ./SockJS.NET/syp.biz/SockJS.NET/syp.biz.SockJS.NET.Common/syp.biz.SockJS.NET.Common.csproj
after_build:
  # For once the build has completed
#artifacts:
# - path: '\src\bin\Debug\netcoreapp1.1\publish'
#   name: WebSite
#   type: WebDeployPackage
on_finish :
  # any cleanup in here
deploy: off
